### PR TITLE
Suggesting to use FIS overview architecture

### PR DESCRIPTION
**Pull request by yiangmeng**
*Issue #, if available:*
#150

*Description of changes:*
- Updated to use generic FIS overview architecture

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by rudpot — COMMENTED** [review]
I like the picture but I don't think that's the right place for it because the architecture picture is too busy to be useful without an explanation. I understand that just putting the FIS icon there is also not ideal either. @adhorn do you have a suggestion for an image/icon that would express the idea of "chaos engineering" without needing as much explanation as the whole architecture diagram?

**Comment by yiangmeng** [comment]
Agreed. How about the "How it works" page for FIS?

https://a.b.cdn.console.awsstatic.com/c4ccf30f133d6149644f62c2cc8483417a13cc0c9d728cb6f3dd9215bb3e58d2/assets/HIW.png

**Comment by rudpot** [comment]
> Agreed. How about the "How it works" page for FIS?
> 
> https://a.b.cdn.console.awsstatic.com/c4ccf30f133d6149644f62c2cc8483417a13cc0c9d728cb6f3dd9215bb3e58d2/assets/HIW.png

Ok, still not ideal but a good middle ground for now. Add it to the PR and I will merge it and they we can see what @adhorn thinks later

**Review by rudpot — APPROVED** [review]
Good middle ground

**Pull request merged**
